### ISSUE TITLE
Ontology construct: SomeValuesFrom/AllValuesFrom

### ISSUE THREAD

**Issue by BlackDark** [VisualDataWeb/OWL2VOWL#12]
Implement new functionality based on the desired visualization in WebVOWL.

Further information of concrete json output will come...

**Comment by steffen-l** [comment]
This is how the visual representation should look like, i.e., like a property relation but with a blue colored line and the symbols for universal and existential quantification instead of cardinalities at the end of the line:

![vowl3-all_somevaluesfrom](https://cloud.githubusercontent.com/assets/12000584/14056163/c5eded0a-f2e8-11e5-9f3c-605d6b0234b5.jpg)

**Comment by steffen-l** [comment]
Note that the same property can be used in multiple such constructs, so that it might appear several times in the graph (on different classes), i.e., it can get multiplied like other elements (datatypes, etc.) in the visualization. All apprearances of the same property might be indicated by indirect highlighting (if the user hovers over one, the other instances of the same property will be highlighted in orange).

**Comment by BlackDark** [comment]
What should happen if we define a property and use it just in restrictions.
For example if we define the ```hasMaker``` property without range/domain.

Based on the specification the property has no domain/range therefore it will be pointing to an owl:Thing.

Additionally we will duplicate the property to draw an restriction between ```Wine``` and ```Winery```?

Based on your example we would have 3 ```hasMaker``` properties. Two showing in the samples and the other one point to a owl:Thing.

Is this correct?

**Comment by steffen-l** [comment]
Good point! It is indeed very common to use someValuesFrom and allValuesFrom instead of domain and range axioms, as the latter are quite restrictive.

In those cases, we do not need to show the property another time with owl:Thing as domain and/or range, i.e., the best would be an extension of the "missing domain and range" rule (defined at http://vowl.visualdataweb.org/v2/#missingDomainOrRange):

"If no domain and/or range axiom [and also no someValuesFrom or someValuesFrom restriction] is defined for a property, owl:Thing should be used as domain and/or range. An exception are datatype properties without a defined range, where rdfs:Literal is used as range instead."

That is, every property must appear at least once. If neither domain and range nor someValuesFrom or someValuesFrom are defined, owl:Thing is used as a workaround, but in all other cases not. Note that a property can appear multiple times, i.e., if defined as domain and range AND with someValuesFrom/allValuesFrom or in multiple someValuesFrom/allValuesFrom constructs.

**Comment by steffen-l** [comment]
If someValuesFrom or allValuesFrom is defined together with a cardinality restriction, the cardinality restriction is simply added with a comma (e.g. "(∃, 2..*)" for someValuesFrom and minCardinality of 2).
