### ISSUE TITLE
owl:complementOf not converted correctly

### ISSUE THREAD

**Issue by linkvt** [VisualDataWeb/OWL2VOWL#15]
When converting an ontology with an `owl:complementOf` construct, the `complement` tag is missing in the generated JSON.

Originally reported in https://github.com/VisualDataWeb/WebVOWL/issues/45

**Comment by steffen-l** [comment]
Good point! It is indeed very common to use someValuesFrom and allValuesFrom instead of domain and range axioms, as the latter are quite restrictive.

In those cases, we do not need to show the property another time with owl:Thing as domain and/or range, i.e., the best would be an extension of the "missing domain and range" rule (defined at http://vowl.visualdataweb.org/v2/#missingDomainOrRange):

"If no domain and/or range axiom [and also no someValuesFrom or someValuesFrom restriction] is defined for a property, owl:Thing should be used as domain and/or range. An exception are datatype properties without a defined range, where rdfs:Literal is used as range instead."

That is, every property must appear at least once. If neither domain and range nor someValuesFrom or someValuesFrom are defined, owl:Thing is used as a placeholder, but in all other cases not. Note that a property can appear multiple times, i.e., if defined with domain and range AND with someValuesFrom/allValuesFrom or in multiple someValuesFrom/allValuesFrom constructs.
