### ISSUE TITLE
Missing info in Selection Details

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/OWL2VOWL#5]
The disjoint classes of the OntoViBe class "LargeDisjointUnionClass" are not shown in the selection details in contrast to the disjoint class of the OntoViBe clas "DisjointClass". This is inconsistent and incorrect.

**Comment by BlackDark** [comment]
@linkvt Also probably WebVOWL related.
In data those relations exists and they dont appear in visualization.
[test.txt](https://github.com/VisualDataWeb/OWL2VOWL/files/96678/test.txt)

**Comment by linkvt** [comment]
As visible in the picture below, there are no disjoint properties connected to the *LargeDisjointUnionClass* in opposite to the *disjoint class*. It's the same with the attached file of the previous comment.

Since *LargeDisjointUnionClass* is a DisjointUnion which is different from disjointWith, OWL2VOWL is probably not splitting the DisjointUnion into disjointWiths and Unions which afaik intended.

![image](https://cloud.githubusercontent.com/assets/3075401/13048060/9e432c76-d3e3-11e5-9d69-611b307969b4.png)
