### ISSUE TITLE
Can't load OWL from my domain

### ISSUE THREAD

**Issue by EmileSonneveld** [VisualDataWeb/OWL2VOWL#51]
No problem when I load the OWL file as a plain text file. But when I load it from an URL to my domain, I get the following error:
```
Loading process failed: 
OWLOntologyCreationIOException: java.io.IOException: Server returned HTTP response code: 401 for URL: https://emilesonneveld.be/dropbox_proxy/slimmerWorden/2018-2019-Semester1/OPEN_INFO/exercises_owl/cinema.owl
```
In the Chrome inspector, this request fails:
http://www.visualdataweb.de/webvowl/convert?iri=https%3A%2F%2Femilesonneveld.be%2Fdropbox_proxy%2FslimmerWorden%2F2018-2019-Semester1%2FOPEN_INFO%2Fexercises_owl%2Fcinema.owl&sessionId=1540216947143
java.lang.NullPointerException

This issue could be related to https://github.com/VisualDataWeb/WebVOWL/issues/95

**Comment by vitalis-wiens** [comment]
I have tried it on my machine, it works (Chrome and Firefox).
Can you try the following link: 

http://www.visualdataweb.de/webvowl/#iri=https://emilesonneveld.be/dropbox_proxy/slimmerWorden/2018-2019-Semester1/OPEN_INFO/exercises_owl/cinema.owl


The link you have provided contains a sessionId.
When requesting a conversion process, we give it  a sessionId.
This allows us to route the conversion progress for the different requests.
After the process has finished the result is returned to webVOWL and the process is killed.

Thus, the link with the session Id is actually asking to access a process that does not exist any more ( the null pointer exception ) 

With respect to the error code : 
HTTP Status Code 401: The request has not been applied because it lacks valid authentication credentials for the target resource. 
But I`m not sure why it works on my side 

I hope this helps, 
Vitalis

**Comment by EmileSonneveld** [comment]
Sorry, I fergot that my dropbox proxy script required authentication. I made it less restrictive now, so that it works. Thanks anyway!
